language: python
python:
- '3.6'
services:
- docker
before_script: pip install docker-compose
script:
- docker-compose run web sh -c "python manage.py test --keepdb && flake8"
deploy:
  provider: heroku
  api_key:
    secure: "gThV4GUtOO57lOzkM1//4vRyv/QKxaxQfI/QVwDheAAI6A/Fk+yM3Ww4Jbcwa6bu06IJRfgTJ1vdASSOZoPanQZ3IWmcKf6jwkB+3RatFdjDDurVJz0ps1hJlYL0x8j6ptCH7ux9LbbF11YkzkvFBbt+THLcdWlfNFmZPwHJKcCu4H3G2CuEJylEO7Bn8LHjBQu6JthQxCjuIUXx2bl4HXPc/cnkNuLEk93nchwoxpqnNIzbLSeNq8ua+AcCNcSKwqkChIUBGWJ5b80padhauQMQSLF4kHlte+V0/HCIbbSRxPdG+6wXIreohTSdTPqN6GvgrkPz8XLHMO0TtsewfBnmJL33qyxBB36/qkpYIJb/dV/cc0Ef5VNMETGCaobdNK3PIUpKOdHnGsR/o5GSA0SutUWrL77dGz1ZMPxSx6Oi48oap1uJgp/LUjq6gsDecff+Li4cEasbfPUNbwcV48ECAOyefOJfPVmKLok7gHcx5OcstE5ViudI3Gac8ITqpQtKUXRJaa1xB6xKxeRarJtUUQ5RLRuD8QPvE0a0u4Coi/fNjgn/4trrz8WFZuD50RPeKL9UbgdM6SbhbkUav5YsmbSQEkV6JpBPHcXwCYJYHoXCID7NBluHpZvsXw/kv6RU57iT7yTxq+rN3WVKVbCU1FbqdBDk1xVHzrBJUYw="
  app: simple-grocery-api
  on:
    repo: pgellert/simple-api
