language: python
python:
  - '3.6'
services:
  - docker
before_script: pip install docker-compose
script:
  - DATABASE_URL=$DATABASE_URL docker-compose run web sh -c "python manage.py test --keepdb && flake8"
deploy:
  provider: heroku
  api_key:
    secure: g9oeIVp9k9jW6mw2POBF9YLVdWAvd8WpbB55w2JrVcCZ8opC1gAUCBw1LJBx6ucd1OPbJYAGGPKfjaqwC2FTHcxuAVPnqkKtXu57YtIwal9sTw3+oIPJGXrN5owrYyGvkZ0d+yG3FjUrVU2Fo68pb/IbsdweMpBhFVSG7vbhxq0eBeDKLHxcgRWcYXw+4T40XkGjE6bJZfA50lCiReL45pmO1FJYqcQ15OQL8lpZWssCxsmDAqj2krkHztXNYWRLrLeR5E89W0KzexsoKFcFtDDc0Nuiu1khyVJ9+XKped6TVcNjQOtQOROFhOFPIBQQBKalNumLXYZ5dtDFapWo0g0wvMbY51MXAgMF7Z2eSfiXH3DO1Yir5614jQYop5UTfhIMu+V89paDLMYioEIoUux+MrIpmdqah38/PjQzTXLjlTGqDmcQ5phYcgZQ937zRhD7bmdHTSxuR1uqJlGPwTlROWJPTDvSMyOt5KDE4IY+YFZPWXfbA4LQ2Uk9dx9wPp9CSqd/wDxFqgvxzIFYXVaj679sMPDBwaGDF1Q8AD8HJVa/4w/cEGYc0O7wTzPza860qBbT4UdX9yRTDsSKB9vNR/xls52GLTmyFguAtrwrm2t+1/sUrrqQ0hqD1M5nHkTglfTIB1+xGGMRWPp2dsacTy4gXG0lVMJGSyrSKjY=
  app: simple-grocery-api
  on:
    repo: pgellert/simple-api
