# Generated by Django 2.1.7 on 2019-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='msg',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
